spring:
  application:
    name: catalog
  webflux:
    base-path: /api
#   data:
#     mongodb:
#       authentication-database: admin
#       uri: mongodb://localhost:27017/test
#       database: test
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    io:
      reflectoring: DEBUG
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG
message:
  topic:
    name: user
